# diffusion hyperparameters
timesteps: 500
beta1: 1e-4
beta2: 0.02

# network hyperparameters
n_feat: 64 # 64 hidden dimension feature
n_cfeat: 5 # context vector is of size 5
height: 256 # 256x256 image
save_dir: "./weights/"

# training hyperparameters
batch_size: 100
n_epoch: 32
lrate: 1e-3
